### ISSUE TITLE
label-format not affecting \cmpd definition globally

### ISSUE THREAD

**Issue by tstone-1** [cgnieder/chemnum#12]
Using chemnum 1.2c, I'm not able to globally alter the `label-format` key. The example

```
\documentclass{article}
\usepackage{chemnum}
\begin{document}

\cmpd*[label-format=\bfseries\textsuperscript,pre-label-code=\textbf{Me\textsubscript{2}L}]{Me2bdc}

\cmpd{Me2bdc}

\end{document}
```

will produce

![Screenshot 2020-02-07 19 13 02](https://user-images.githubusercontent.com/48162401/74054239-f2e64a00-49dd-11ea-8311-0371d30cded6.png),

where the compound label 1 should be typeset in `\textsuperscript`, I guess.

I've reported this issue on StackExchange including a (slightly extended) example before: https://tex.stackexchange.com/questions/527398/chemnum-label-format-not-affecting-cmpd-definition-globally

**Comment by cgnieder** [comment]
This is not a bug, see my answer on tex.sx.
If you want this to be a feature please let me know and I'll open the issue again.
