### ISSUE TITLE
feature request: setting label-format compound-wise

### ISSUE THREAD

**Issue by tstone-1** [cgnieder/chemnum#13]
There are cases where it might be very desirable to set the `label-format` compound-wise on declaration of the respective compound. This question was discussed [here](https://tex.stackexchange.com/questions/527398/chemnum-label-format-not-affecting-cmpd-definition-globally) previously. It was suggested to use grouping in order to restrict `\bfseries\textsuperscript` to apply to only few of the compounds used within the document.

The example
```
\documentclass{article}
\usepackage{chemnum}
\usepackage{auto-pst-pdf}
\begin{document}

\begingroup
\setchemnum{format=\bfseries\textsuperscript}
\cmpd*[pre-label-code=\textbf{H\textsubscript{2}L}]{H2bdc}
\resetcmpd
\cmpd*[pre-label-code=\textbf{Me\textsubscript{2}L}]{Me2bdc}
\endgroup
\cmpd*{benzene}

\noindent This is about compounds \cmpd{H2bdc} and \cmpd{Me2bdc}.\\
Compound \cmpd{benzene} should not be typeset fancy

\begin{figure}[h]
\replacecmpd[tag=H2bdc]{H2bdc}
\replacecmpd[tag=Me2bdc]{Me2bdc}
\replacecmpd[tag=benzene]{benzene}
\includegraphics{./mwe.eps}
\end{figure}

\end{document}
```

will produce on calling `pdflatex --shell-escape mwe.tex`:

![Screenshot 2020-02-07 22 19 26](https://user-images.githubusercontent.com/48162401/74066737-ff779c00-49f7-11ea-9ce2-e4215a663ee2.png)

While the rendering of compounds `H2bdc`, `Me2bdc`, and `benzene` looks fine within text, the replacement within the eps file does not follow the desired style.

The eps example file was added to a zip archive and is available here: [mwe.zip](https://github.com/cgnieder/chemnum/files/4172987/mwe.zip)

**Comment by cgnieder** [comment]
If I am not completely mistaken this is a support question about a problem you have *and not* a feature request. (Correct me if I'm wrong.)

May I suggest a different approach which avoids all problems. This is not a problem of *formatting* but about distinct *labels*, right?

```latex
% arara: pdflatex: { interaction: nonstopmode , shell: on }
\documentclass{article}
\usepackage{chemnum}
\usepackage[version=4]{mhchem}
\usepackage{auto-pst-pdf}

\ExplSyntaxOn
\NewDocumentCommand \setcmpdlabel {mm}
  { \chemnum_compound_set_property:nnn {#1} {counter-representation} {#2} }
\ExplSyntaxOff

\begin{document}

\cmpd*{H2bdc}
\setcmpdlabel{H2bdc}{\ce{H2L^1}}
\cmpd*{Me2bdc}
\setcmpdlabel{Me2bdc}{\ce{Me2L^1}}

\resetcmpd[2]

\cmpd*{benzene}

This is about compounds \cmpd{H2bdc} and \cmpd{Me2bdc}.  Compound
\cmpd{benzene} should not be typeset fancy

\begin{figure}
  \replacecmpd[tag=H2bdc]{H2bdc}
  \replacecmpd[tag=Me2bdc]{Me2bdc}
  \replacecmpd[tag=benzene]{benzene}
  \includegraphics{./mwe.eps}
\end{figure}

\end{document}
```

![image](https://user-images.githubusercontent.com/2248538/74085093-e4e40800-4a75-11ea-9e07-db1c3c172e96.png)

**Comment by tstone-1** [comment]
Maybe you are right and this is more like a support request - obviously there is much more doable than I realized before! I would like to add one more example (employing the procedure as suggested by you), maybe this is helpful for others as well:

```
% arara: pdflatex: { interaction: nonstopmode , shell: on }

\documentclass{article}
\usepackage{chemnum}
\usepackage{chemformula}
\usepackage{auto-pst-pdf}

\ExplSyntaxOn
\NewDocumentCommand \setcmpdlabel {mm}
  { \chemnum_compound_set_property:nnn {#1} {counter-representation} {#2} }
\ExplSyntaxOff

\begin{document}

\cmpd*{Me2bdc}
\setcmpdlabel{Me2bdc}{\ch{Me2L^1}}
\cmpd*{H2bdc}
\setcmpdlabel{H2bdc}{\ch{H2L^1}}
\cmpd*{bdc}
\setcmpdlabel{bdc}{L\textsuperscript{1}}

\resetcmpd[2]
\cmpd*{benzene}
\cmpd*{mof5}
\setcmpdlabel{mof5}{MOF-5}

\noindent \cmpd{Me2bdc} yields \cmpd{H2bdc} after saponification. While \cmpd{benzene} is totally unrelated, the solvothermal reaction between \cmpd{H2bdc} and a suitable Zn(II) salt will yield \cmpd{mof5} with a formula sum of \ch{[Zn4O\cmpd{bdc}3(dmf)_{\textit{x}}]} (\textit{x} = 1--2).

\begin{figure}[h]
\replacecmpd[tag=Me2bdc]{Me2bdc}
\replacecmpd[tag=H2bdc]{H2bdc}
\replacecmpd[tag=benzene]{benzene}
\replacecmpd[tag=mof5]{mof5}
\includegraphics{./mwe.eps}
\end{figure}

\end{document}
```

![Screenshot 2020-02-09 14 48 08](https://user-images.githubusercontent.com/48162401/74103341-9ef97380-4b4b-11ea-9986-bdb16754e772.png)

This is why that formalism might be of use: One can now use L^1 as part of a compositional formula. If, however, one tries to use `\setcmpdlabel{bdc}{\ch{L^1}}` instead of `\setcmpdlabel{bdc}{L\textsuperscript{1}}`, pdflatex will end in error:

```
! TeX capacity exceeded, sorry [grouping levels=255].
<recently read> {
                 
l.27 ...f \ch{[Zn4O\cmpd{bdc}3(dmf)_{\textit{x}}]}
                                                   (\textit{x} = 1--2).
If you really absolutely need more capacity,
you can ask a wizard to enlarge me.
```

I'm interested in what's going wrong here...? Nevertheless, I would like to thank you for your years of effort, especially for the chem* packages and acro, as well as your help with those!

**Comment by cgnieder** [comment]
When you do `\setcmpdlabel{bdc}{\ch{L^1}}` and after that `\ch{...\cmpd{bdc}...}` this is more or less equivalent to `\ch{...\ch{...}...}` which leads to the same error. IIRC the `chemformula` manual states that `\ch` cannot be nested!

- You can try `\setcmpdlabel{bdc}{\chcpd{L^1}}`
- You should probably also use `chemformula`'s escape mechanism (and math mode where math mode is due): `\ch{[Zn4O "\cmpd{bdc}" 3(dmf)_{$x$}]}`

**Comment by tstone-1** [comment]
(is it possible to reply to closed issues?)

I found the solution developed herein to be very convenient. However, the representation within the ToC of the PDF is not yet satisfying. Thought that `\cmpdplain` in combination with `\texorpdfstring` should be used here. However,

```
% arara: pdflatex

\documentclass{article}
\usepackage{chemnum}
\usepackage{chemformula}
\usepackage{hyperref}

\ExplSyntaxOn
\NewDocumentCommand \setcmpdlabel {mm}
  { \chemnum_compound_set_property:nnn {#1} {counter-representation} {#2} }
\ExplSyntaxOff

\cmpd*{Me2bdc}
\setcmpdlabel{Me2bdc}{\ch{Me2L^1}}
\cmpd*{H2bdc}
\setcmpdlabel{H2bdc}{\ch{H2L^1}}

\begin{document}

\section{About \texorpdfstring{\cmpd{Me2bdc}}{\cmpdplain{Me2bdc}}}
Lorem ipsum.

\section{About \texorpdfstring{\cmpd{H2bdc}}{\cmpdplain{H2bdc}}}
Lorem ipsum.

\end{document}
```
will produce:
![Screenshot 2020-04-02 19 33 37](https://user-images.githubusercontent.com/48162401/78280206-04009280-7519-11ea-8b68-56f2b9be81bc.png)

Do you have a good suggestion on how to handle this? Thanks - as always!

**Comment by tstone-1** [comment]
Another hint for those of you that want to use the .eps replacement with the method discussed herein... You might want to adjust the replacement positions:

```
% arara: pdflatex: { shell : yes }

\documentclass{article}
\usepackage{chemnum}
\usepackage{graphicx}
\usepackage{auto-pst-pdf}

\ExplSyntaxOn
\NewDocumentCommand \setcmpdlabel {mm}
  { \chemnum_compound_set_property:nnn {#1} {counter-representation} {#2} }
\ExplSyntaxOff

\begin{document}

\cmpd*{PhCOOMe}
\setcmpdlabel{PhCOOMe}{MeL}
\cmpd*{PhCOOH}
\setcmpdlabel{PhCOOH}{HL}

\cmpd*{PhCOOMe2}
\setcmpdlabel{PhCOOMe2}{Me\textsubscript{1}L\textsuperscript{1}}
\cmpd*{PhCOOH2}
\setcmpdlabel{PhCOOH2}{HL\textsuperscript{1}}

\begin{figure}[h]
	\replacecmpd[tag=PhCOOMe]{PhCOOMe}
	\replacecmpd[tag=PhCOOH]{PhCOOH}
	\includegraphics[scale=1]{./mwe.eps}
\end{figure}

\begin{figure}[h]
	\replacecmpd[tag=PhCOOMe]{PhCOOMe2}
	\replacecmpd[tag=PhCOOH]{PhCOOH2}
	\includegraphics[scale=1]{./mwe.eps}
\end{figure}

\setchemnum{replace-pos=Bb}
\setchemnum{pos=Bb}

\begin{figure}[h]
	\replacecmpd[tag=PhCOOMe]{PhCOOMe2}
	\replacecmpd[tag=PhCOOH]{PhCOOH2}
	\includegraphics[scale=1]{./mwe.eps}
\end{figure}

\end{document}
```

will produce:

![Screenshot 2020-04-11 22 05 20](https://user-images.githubusercontent.com/48162401/79053835-aa971280-7c40-11ea-9fc1-409a70060253.png)
