### ISSUE TITLE
\setcmpdlabel method: how to bring user-defined labels to PDF bookmarks?

### ISSUE THREAD

**Issue by tstone-1** [cgnieder/chemnum#15]
Transparency notice: The problem was already described [here](https://github.com/cgnieder/chemnum/issues/13#issuecomment-607989686).

I'm using the `\setcmpdlabel` approach (initially proposed by the package author [here](https://tex.stackexchange.com/a/170196/18258)) to generate custom labels of compounds. This works fine for me with one notable exception: I can't find a proper way to represent the custom labels within PDF bookmarks.

```
% arara: pdflatex

\documentclass{article}
\usepackage{chemnum}
\usepackage{chemformula}
\usepackage{hyperref}

\ExplSyntaxOn
\NewDocumentCommand \setcmpdlabel {mm}
  { \chemnum_compound_set_property:nnn {#1} {counter-representation} {#2} }
\ExplSyntaxOff

\cmpd*{Me2bdc}
\setcmpdlabel{Me2bdc}{\ch{Me2L^1}}
\cmpd*{H2bdc}
\setcmpdlabel{H2bdc}{\ch{H2L^1}}

\begin{document}

\section{About \texorpdfstring{\cmpd{Me2bdc}}{\cmpdplain{Me2bdc}}}
Lorem ipsum.

\section{About \texorpdfstring{\cmpd{H2bdc}}{\cmpdplain{H2bdc}}}
Lorem ipsum.

\end{document}
```

will produce:

![78280206-04009280-7519-11ea-8b68-56f2b9be81bc](https://user-images.githubusercontent.com/48162401/81507155-a885a980-92fb-11ea-8227-18b11f7d6857.png)

The section titles will be numerical and not represent the user-defined compound label. Also tried to use `\cmpdproperty{H2bdc}{counter-representation}`, unfortunately no success. Help is greatly appreciated! Thanks.

**Comment by tstone-1** [comment]
Ulrike Fischer came up with a viable solution [here](https://tex.stackexchange.com/a/548244/18258).

**Comment by cgnieder** [comment]
Thanks. Fixed for the next update. The problem was that the compound declarations were not written to the aux file in this case.
