### ISSUE TITLE
Indicate missing sublabel

### ISSUE THREAD

**Issue by lcnittl** [cgnieder/chemnum#5]
If a normal cmpd label is missing, two questionmarks are placed in the document, if a sublabel is missing, there is no indication.

**MWE**

    \documentclass{report}
    
    \usepackage{chemnum}
    
    \begin{document}
      Compound \cmpd{nicecmpd} had a nice color. Compound \cmpd+{2} has not been defined and I see two questionmarks, however, I'm not informed that the subcompound \cmpd+{nicecmpd.derivate1}  does not exist. It could for example output "\cmpd+{nicecmpd}??".
    \end{document}

![image](https://user-images.githubusercontent.com/23134999/32082702-b0f8ca7a-babd-11e7-9547-07ca0dd6a638.png)

I think it would be a nice enhancement to alter the output if a sublabel is missing.

**Comment by cgnieder** [comment]
Hm, this *is* implemented:

```latex
\cs_new_protected:Npn \chemnum_subcompound_read:nn #1#2
  {
    \group_begin:
      \bool_if:NTF \l__chemnum_compound_local_bool
        { \l__chemnum_local_label_format_tl }
        { \chemnum_get_compound_property:nn {#1} {previous-label-format} }
      {
        \chemnum_get_subcompound_property_or:nnnn {#1} {#2}
          {previous-counter-representation}
          { ?? \__chemnum_rerun: }
      }
    \group_end:
  }
```

so there is something unexpected going on…

**Comment by lcnittl** [comment]
That's weird then. Thanks for having a look!
